# Generated by Django 5.0.6 on 2024-06-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageVisits',
            new_name='PageVisit',
        ),
    ]
